import { Center, Group, Text } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Download: NextPage = () => {
  return (
    <>
      <Head>
        <title>{`Resumake Support`}</title>
        <meta name="apple-itunes-app" content="app-id=6444913161" />
        <meta name="description" content="Generated by create-t3-app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0"
        />
        <meta property="og:image" content="/images/jpg/link_preview.jpg" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Center
          style={{
            height: "100vh",
          }}
        >
          <Group align="center">
            <Text>
              Contact out support email at{" "}
              <Link href="mailto:support@hntr.io">support@hntr.io</Link>
            </Text>
          </Group>
        </Center>
      </main>
    </>
  );
};

export default Download;
